"""
Protocol definitions for all repository classes.

These are structural (duck-typed) protocols — existing repo classes satisfy them
without any code changes. Use these types in service __init__ signatures so that
tests can inject fakes without patching.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional, Protocol, runtime_checkable

from app.models.asset import Asset, AssetType, AssetClass
from app.models.transaction import Transaction
from app.models.valuation import Valuation
from app.models.price_cache import PriceCache
from app.models.fd_detail import FDDetail
from app.models.cas_snapshot import CasSnapshot
from app.models.goal import Goal, GoalAllocation
from app.models.snapshot import PortfolioSnapshot


@runtime_checkable
class IAssetRepository(Protocol):
    def create(self, **kwargs) -> Asset: ...
    def get_by_id(self, asset_id: int) -> Optional[Asset]: ...
    def list(
        self,
        asset_type: Optional[AssetType] = None,
        asset_class: Optional[AssetClass] = None,
        active: Optional[bool] = None,
    ) -> list[Asset]: ...
    def update(self, asset: Asset, **kwargs) -> Asset: ...
    def soft_delete(self, asset: Asset) -> Asset: ...
    def list_unmatured_past_maturity(self) -> list[Asset]: ...


@runtime_checkable
class ITransactionRepository(Protocol):
    def create(self, **kwargs) -> Transaction: ...
    def get_by_txn_id(self, txn_id: str) -> Optional[Transaction]: ...
    def get_by_id(self, transaction_id: int) -> Optional[Transaction]: ...
    def list_by_asset(self, asset_id: int) -> list[Transaction]: ...
    def list_by_asset_paginated(self, asset_id: int, page: int, page_size: int) -> list[Transaction]: ...
    def count_by_asset(self, asset_id: int) -> int: ...
    def list_all(self) -> list[Transaction]: ...
    def update(self, txn: Transaction, **kwargs) -> Transaction: ...
    def delete(self, txn: Transaction) -> None: ...


@runtime_checkable
class IValuationRepository(Protocol):
    def create(self, **kwargs) -> Valuation: ...
    def get_by_id(self, valuation_id: int) -> Optional[Valuation]: ...
    def list_by_asset(self, asset_id: int) -> list[Valuation]: ...
    def delete(self, val: Valuation) -> None: ...


@runtime_checkable
class IPriceCacheRepository(Protocol):
    def get_by_asset_id(self, asset_id: int) -> Optional[PriceCache]: ...
    def upsert(
        self,
        asset_id: int,
        price_inr: int,
        source: str,
        fetched_at: Optional[datetime] = None,
        is_stale: bool = False,
    ) -> PriceCache: ...


@runtime_checkable
class IFDRepository(Protocol):
    def create(self, **kwargs) -> FDDetail: ...
    def get_by_asset_id(self, asset_id: int) -> Optional[FDDetail]: ...
    def update(self, fd: FDDetail, **kwargs) -> FDDetail: ...


@runtime_checkable
class ICasSnapshotRepository(Protocol):
    def create(
        self,
        asset_id: int,
        date: date,
        closing_units: float,
        nav_price_inr: int,
        market_value_inr: int,
        total_cost_inr: int,
    ) -> CasSnapshot: ...
    def get_latest_by_asset_id(self, asset_id: int) -> Optional[CasSnapshot]: ...


@runtime_checkable
class IGoalRepository(Protocol):
    def create(self, **kwargs) -> Goal: ...
    def get_by_id(self, goal_id: int) -> Optional[Goal]: ...
    def list_all(self) -> list[Goal]: ...
    def update(self, goal: Goal, **kwargs) -> Goal: ...
    def delete(self, goal: Goal) -> None: ...
    def create_allocation(self, **kwargs) -> GoalAllocation: ...
    def get_allocation(self, goal_id: int, asset_id: int) -> Optional[GoalAllocation]: ...
    def list_allocations_for_goal(self, goal_id: int) -> list[GoalAllocation]: ...
    def list_allocations_for_asset(self, asset_id: int) -> list[GoalAllocation]: ...
    def delete_allocation(self, alloc: GoalAllocation) -> None: ...


@runtime_checkable
class ISnapshotRepository(Protocol):
    def upsert(self, snapshot_date: date, total_value_paise: int, breakdown_json: str) -> PortfolioSnapshot: ...
    def list(self, from_date: Optional[date] = None, to_date: Optional[date] = None) -> list[PortfolioSnapshot]: ...
    def get_by_date(self, snapshot_date: date) -> Optional[PortfolioSnapshot]: ...
