"""add_mfapi_scheme_code_to_assets

Revision ID: 0453f3ff0410
Revises: cc5e17817e4b
Create Date: 2026-03-19 21:54:48.598969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0453f3ff0410'
down_revision: Union[str, None] = 'cc5e17817e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('mfapi_scheme_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'mfapi_scheme_code')
    # ### end Alembic commands ###
