"""add_portfolio_snapshots

Revision ID: 2788f59d52d0
Revises: 0453f3ff0410
Create Date: 2026-03-20 16:47:09.279564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2788f59d52d0'
down_revision: Union[str, None] = '0453f3ff0410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
