"""add_scheme_category_fix_nps_asset_class

Revision ID: 5bcf15222da5
Revises: 943d28bd8a1b
Create Date: 2026-03-24 16:18:50.317320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcf15222da5'
down_revision: Union[str, None] = '943d28bd8a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('scheme_category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###
    # Fix existing NPS assets: MIXED → DEBT
    op.execute("UPDATE assets SET asset_class = 'DEBT' WHERE asset_type = 'NPS'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE assets SET asset_class = 'MIXED' WHERE asset_type = 'NPS'")
    op.drop_column('assets', 'scheme_category')
    # ### end Alembic commands ###
