"""add_cas_snapshots_table

Revision ID: 943d28bd8a1b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 11:57:56.442516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943d28bd8a1b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cas_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('closing_units', sa.Float(), nullable=False),
    sa.Column('nav_price_inr', sa.Integer(), nullable=False),
    sa.Column('market_value_inr', sa.Integer(), nullable=False),
    sa.Column('total_cost_inr', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cas_snapshots_asset_id'), 'cas_snapshots', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cas_snapshots_id'), 'cas_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cas_snapshots_id'), table_name='cas_snapshots')
    op.drop_index(op.f('ix_cas_snapshots_asset_id'), table_name='cas_snapshots')
    op.drop_table('cas_snapshots')
    # ### end Alembic commands ###
